version: "3"
services:
  findbook:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    volumes:
      - d:\BAS\github\Java\findbook\outLib\:/outLib/
  mysqldb:
    build: ./src/main/sql
    volumes:
      - my_volume:/var/lib/mysql
volumes:
  my_volume: